"""
Build script: generates the full expanded content.json for Exams I & II.
Run: python build_content.py
"""
import json

with open("src/data/content.json", "r", encoding="utf-8") as f:
    data = json.load(f)

def fc(id, section, front, back, diff):
    return {"id": id, "section": section, "front": front, "back": back,
            "difficulty": diff, "image": None}

def q(id, section, question, choices, ai, explanation, diff):
    return {"id": id, "section": section, "question": question, "choices": choices,
            "answerIndex": ai, "explanation": explanation, "difficulty": diff, "image": None}

# ─────────────────────────────────────────────────────────────────────────────
# ADDITIONS TO EXISTING CHAPTERS
# ─────────────────────────────────────────────────────────────────────────────

ch1_extra_quiz = [
    q("ch1-q-008", "1.3",
      "A study tests a drug on only 5 people. A critic says the sample is too small. Why does sample size matter?",
      ["Larger samples make experiments faster",
       "Larger samples reduce the chance that results are due to random variation, making conclusions more reliable",
       "Smaller samples are always more accurate",
       "Sample size only matters in observational studies"],
      1,
      "A larger sample size reduces the probability that an outcome is due to chance rather than the variable being tested, increasing the statistical reliability of the conclusion.",
      "medium"),

    q("ch1-q-009", "1.3",
      "In a double-blind drug trial, neither patients nor researchers know who received the real drug. This design eliminates:",
      ["The need for a control group",
       "Observer bias and the placebo effect from skewing results",
       "The need for statistical analysis",
       "Ethical concerns about the experiment"],
      1,
      "Double-blind design prevents researchers from unconsciously influencing data collection (observer bias) and prevents patients from feeling better simply because they believe they are being treated (placebo effect).",
      "medium"),

    q("ch1-q-010", "1.1",
      "At which level of biological organization does LIFE first appear — the simplest unit considered to be alive?",
      ["Molecule", "Organelle", "Cell", "Tissue"],
      2,
      "The cell is the basic unit of life. Molecules and organelles are essential components but are not alive on their own. No level below the cell meets all five characteristics of life.",
      "easy"),

    q("ch1-q-011", "1.2",
      "Which domain includes ALL organisms whose cells contain membrane-bound nuclei?",
      ["Bacteria", "Archaea", "Eukarya", "Prokaryota"],
      2,
      "Eukarya — protists, fungi, plants, and animals — all have membrane-bound nuclei. Bacteria and Archaea are prokaryotic; their DNA resides in a nucleoid region, not a membrane-bound nucleus.",
      "easy"),

    q("ch1-q-012", "1.3",
      "A researcher watches lions hunt in the wild and records prey choices without changing anything. This study is:",
      ["A controlled experiment with a treatment group",
       "An observational study — no variables were manipulated",
       "A double-blind experiment",
       "A case study with a placebo group"],
      1,
      "An observational (descriptive) study records what occurs in nature without manipulating variables. It can identify correlations but cannot establish cause-and-effect on its own.",
      "medium"),

    q("ch1-q-013", "1.3",
      "Natural selection acts on _______, but evolution is a change in _______ over generations.",
      ["populations; individual traits",
       "individuals; allele frequencies in populations",
       "alleles; single organisms",
       "species; ecosystems"],
      1,
      "Natural selection acts on heritable variation among individuals. Evolution, however, is defined at the population level as a change in allele frequencies over time — not change within a single organism.",
      "hard"),

    q("ch1-q-014", "1.3",
      "What is the primary purpose of peer review before scientific publication?",
      ["To make research available to the public faster",
       "To secure funding for future experiments",
       "To have independent experts evaluate methods, data, and conclusions for errors and bias",
       "To ensure the researcher is compensated"],
      2,
      "Peer review is science's quality-control system: independent experts critique the study's design, data, and interpretation before publication, catching errors and preventing flawed findings from entering the literature.",
      "easy"),

    q("ch1-q-015", "1.3",
      "A classmate says, 'Evolution is just a theory — it might not be true.' The best scientific response is:",
      ["Agree; theories are unproven guesses that could easily be wrong",
       "In science, a theory is the highest-confidence explanation: broad, predictive, and supported by many independent lines of evidence",
       "A theory becomes a fact once enough scientists accept it",
       "Theories only apply to simple phenomena, not complex ones like evolution"],
      1,
      "In everyday speech, 'theory' means a guess. In science, a theory is a rigorously tested, broadly supported explanation with predictive power. The theory of evolution is backed by the fossil record, molecular biology, biogeography, and observed speciation.",
      "medium"),
]

ch2_extra_quiz = [
    q("ch2-q-009", "2.3",
      "Why does water resist temperature change — what gives it a high specific heat?",
      ["Water molecules are unusually large and dense",
       "Hydrogen bonds between water molecules must be broken to raise temperature, absorbing large amounts of energy",
       "Water is a nonpolar solvent",
       "Water has a low boiling point relative to its molecular weight"],
      1,
      "To increase water's temperature, hydrogen bonds between molecules must be disrupted before kinetic energy increases. This requires a large energy input, buffering temperature changes in cells and ecosystems.",
      "medium"),

    q("ch2-q-010", "2.5",
      "Which polysaccharide is the primary long-term energy storage molecule in animal cells?",
      ["Starch", "Glycogen", "Cellulose", "Chitin"],
      1,
      "Glycogen is a highly branched polysaccharide stored in animal liver and muscle. Starch is the plant energy-storage equivalent. Cellulose is structural in plant cell walls; chitin is structural in fungal cell walls and arthropod exoskeletons.",
      "medium"),

    q("ch2-q-011", "2.5",
      "A nucleotide — the monomer of DNA and RNA — consists of which three components?",
      ["Amino acid + phosphate + ribose",
       "Nitrogenous base + 5-carbon sugar + phosphate group",
       "Glycerol + fatty acid + nitrogenous base",
       "Monosaccharide + peptide bond + phosphate"],
      1,
      "Every nucleotide contains: a nitrogenous base (A, T, G, C in DNA; U replaces T in RNA), a pentose sugar (deoxyribose in DNA; ribose in RNA), and one or more phosphate groups.",
      "medium"),

    q("ch2-q-012", "2.5",
      "Which bond joins amino acids together in a polypeptide chain?",
      ["Hydrogen bond", "Ionic bond", "Peptide bond", "Disulfide bond"],
      2,
      "Dehydration synthesis between the -COOH of one amino acid and the -NH2 of the next forms a peptide bond, releasing water. This defines the primary structure. Disulfide bonds stabilize 3D shape but do not link the backbone.",
      "easy"),

    q("ch2-q-013", "2.4",
      "Blood pH drops from 7.4 to 7.1 during acidosis. What happened to hydrogen ion concentration [H+]?",
      ["[H+] decreased — blood became less acidic",
       "[H+] increased — blood became more acidic",
       "[H+] stayed the same; only OH- changed",
       "[H+] changed by exactly 0.3 units"],
      1,
      "pH is the negative log of [H+], so lower pH = higher [H+]. Each unit is a 10-fold change; a drop of 0.3 units nearly doubles [H+]. This acidosis disrupts enzyme function throughout the body and is life-threatening.",
      "hard"),
]

ch3_extra_quiz = [
    q("ch3-q-010", "3.4",
      "Mitochondria have their own circular DNA and divide by binary fission inside the cell. This evidence best supports:",
      ["The fluid mosaic model of the plasma membrane",
       "The endosymbiotic theory — mitochondria descended from engulfed prokaryotes",
       "The third principle of cell theory (cells come from cells)",
       "The lock-and-key model of enzyme specificity"],
      1,
      "The endosymbiotic theory (Lynn Margulis) proposes mitochondria and chloroplasts were once free-living bacteria engulfed by a larger host cell. Evidence: circular DNA, double membrane, 70S ribosomes like bacteria, and binary fission.",
      "medium"),

    q("ch3-q-011", "3.4",
      "If lysosomal hydrolytic enzymes leaked out of their vesicles into the cytoplasm, the most likely outcome would be:",
      ["Faster cell growth from additional nutrients",
       "Increased ATP production",
       "Digestion of the cell's own proteins and organelles, leading to cell death",
       "Immediate export of the enzymes by exocytosis"],
      2,
      "Lysosomes contain hydrolytic enzymes optimized for low pH. Released into the neutral cytoplasm they would begin digesting the cell's own macromolecules and organelles — a basis of certain cell-death and disease pathways.",
      "medium"),

    q("ch3-q-012", "3.4",
      "Which cytoskeletal component forms the mitotic spindle that separates chromosomes during cell division?",
      ["Microfilaments (actin)",
       "Intermediate filaments",
       "Microtubules (tubulin polymers)",
       "The nuclear lamina"],
      2,
      "Microtubules polymerize from tubulin subunits and form the spindle apparatus. They attach to chromosomes at kinetochores and shorten during anaphase to pull sister chromatids to opposite poles.",
      "medium"),

    q("ch3-q-013", "3.3",
      "A plant cell placed in a hypertonic solution will:",
      ["Gain water and become turgid",
       "Lose water; the membrane shrinks away from the cell wall (plasmolysis)",
       "Stay the same — the cell wall prevents any water movement",
       "Burst due to osmotic pressure"],
      1,
      "In a hypertonic solution, water exits the plant cell by osmosis. The cytoplasm and membrane shrink away from the rigid cell wall — plasmolysis. Unlike animal cells, plant cells do not burst in hypotonic solutions because the wall resists expansion.",
      "medium"),

    q("ch3-q-014", "3.2",
      "Which three structures are found in plant cells but NOT in typical animal cells?",
      ["Nucleus, mitochondria, and ribosomes",
       "Plasma membrane, cytoplasm, and Golgi",
       "Cell wall, chloroplasts, and large central vacuole",
       "Cytoskeleton, ER, and lysosomes"],
      2,
      "Plant cells uniquely possess: a cellulose cell wall (rigid support), chloroplasts (photosynthesis), and a large central vacuole (water storage, turgor pressure, waste storage). Animal cells lack all three.",
      "easy"),
]

# ─────────────────────────────────────────────────────────────────────────────
# CHAPTER 4 — THE ENERGY OF LIFE
# ─────────────────────────────────────────────────────────────────────────────
ch4 = {
    "id": "ch4",
    "title": "The Energy of Life",
    "sections": [
        {"id": "4.1", "title": "All Living Things Use Energy"},
        {"id": "4.2", "title": "ATP Is the Cell's Energy Currency"},
        {"id": "4.3", "title": "Enzymes Speed Reactions"},
        {"id": "4.4", "title": "Membrane Transport"},
    ],
    "flashcards": [
        fc("ch4-fc-001", "4.1",
           "First Law of Thermodynamics",
           "Energy cannot be created or destroyed, only converted from one form to another. Cells cannot manufacture energy; they convert chemical energy in food into ATP, heat, and work.",
           "medium"),

        fc("ch4-fc-002", "4.1",
           "Second Law of Thermodynamics and entropy",
           "Every energy conversion increases entropy (disorder) in the universe. Cells must constantly import energy because each chemical reaction dissipates some energy as heat. Life maintains local order only by continuously using energy.",
           "medium"),

        fc("ch4-fc-003", "4.1",
           "Exergonic vs. endergonic reaction",
           "Exergonic: releases free energy (delta G < 0); products have less energy than reactants; spontaneous (e.g., respiration). Endergonic: requires energy input (delta G > 0); products have more energy (e.g., building glucose). Coupled reactions pair the two.",
           "medium"),

        fc("ch4-fc-004", "4.2",
           "ATP structure",
           "Adenosine triphosphate = adenine + ribose + 3 phosphate groups. The bond between the second and third phosphates stores potential energy. ATP is the universal energy currency of all cells.",
           "easy"),

        fc("ch4-fc-005", "4.2",
           "ATP hydrolysis reaction and energy yield",
           "ATP + H2O -> ADP + Pi + energy (~7.3 kcal/mol). Breaking the terminal phosphate bond releases free energy that drives cellular work: muscle contraction, active transport, biosynthesis. ADP is recharged back to ATP by cellular respiration.",
           "medium"),

        fc("ch4-fc-006", "4.2",
           "Substrate-level vs. oxidative phosphorylation",
           "Substrate-level phosphorylation: ATP made by directly transferring a phosphate from a substrate to ADP (e.g., in glycolysis and Krebs cycle). Oxidative phosphorylation: ATP made using energy from an electron transport chain + chemiosmosis (inner mitochondrial membrane).",
           "hard"),

        fc("ch4-fc-007", "4.3",
           "Activation energy and how enzymes lower it",
           "Activation energy (Ea) is the minimum energy required to start a reaction. Enzymes lower Ea by orienting substrates, stressing bonds, and providing a favorable microenvironment. They do NOT change the overall delta G of the reaction.",
           "medium"),

        fc("ch4-fc-008", "4.3",
           "Active site, substrate, and enzyme-substrate complex",
           "The active site is the specific region on an enzyme where substrate binds. Substrate + enzyme -> enzyme-substrate complex -> products released + enzyme recycled. Active-site shape is complementary to the substrate.",
           "easy"),

        fc("ch4-fc-009", "4.3",
           "Induced fit model",
           "When the substrate enters the active site, the enzyme changes shape slightly to grip the substrate more tightly. This induced fit differs from the rigid 'lock-and-key' model and better explains why enzymes are specific yet flexible.",
           "medium"),

        fc("ch4-fc-010", "4.3",
           "Temperature and pH effects on enzymes",
           "Each enzyme has an optimal temperature and pH. Too hot: denaturation (weak bonds break, protein unfolds, active site lost). Too cold: slower reaction rate. Wrong pH: denatures enzyme or disrupts substrate binding. Human body enzymes optimal near 37 degrees C and pH 7.4.",
           "medium"),

        fc("ch4-fc-011", "4.3",
           "Cofactors vs. coenzymes",
           "Cofactors: inorganic ions (Mg2+, Zn2+, Fe2+) that assist enzyme catalysis. Coenzymes: organic non-protein helpers (NAD+, FAD, coenzyme A; many derived from vitamins) that carry chemical groups or electrons between reactions. Both are required for enzyme function.",
           "hard"),

        fc("ch4-fc-012", "4.3",
           "Competitive inhibitor",
           "Structurally resembles the substrate; competes for the ACTIVE SITE. Reversible: increasing substrate concentration can displace the inhibitor. Example: statins compete with the normal substrate of HMG-CoA reductase, reducing cholesterol synthesis.",
           "medium"),

        fc("ch4-fc-013", "4.3",
           "Non-competitive (allosteric) inhibitor",
           "Binds the ALLOSTERIC SITE (not the active site), causing a conformational change that reduces enzyme activity. Cannot be overcome by adding more substrate. Allosteric regulation allows end-product feedback to shut off a metabolic pathway.",
           "medium"),

        fc("ch4-fc-014", "4.4",
           "Simple diffusion",
           "Net movement of a substance from HIGH to LOW concentration, driven by the concentration gradient. Passive — no ATP needed. Reaches equilibrium when concentrations equalize. Small, nonpolar molecules (O2, CO2) diffuse freely through the lipid bilayer.",
           "easy"),

        fc("ch4-fc-015", "4.4",
           "Osmosis",
           "Diffusion of WATER through a selectively permeable membrane from LOW solute (high water) to HIGH solute (low water) concentration. Passive. Continues until solute concentrations equalize or pressure builds to oppose it (osmotic pressure).",
           "medium"),

        fc("ch4-fc-016", "4.4",
           "Isotonic, hypotonic, hypertonic — effects on animal cells",
           "Isotonic: same solute outside as inside — no net water movement. Hypotonic: less solute outside — water enters, cell swells; may lyse (osmotic lysis). Hypertonic: more solute outside — water leaves, cell shrinks (crenation). IV fluids must be isotonic.",
           "medium"),

        fc("ch4-fc-017", "4.4",
           "Facilitated diffusion vs. active transport",
           "Facilitated diffusion: PASSIVE; channel or carrier proteins; HIGH to LOW concentration; no ATP (e.g., glucose via GLUT transporters). Active transport: requires ATP; pump proteins; moves AGAINST gradient LOW to HIGH (e.g., Na+/K+ pump).",
           "medium"),

        fc("ch4-fc-018", "4.4",
           "Sodium-potassium (Na+/K+) pump",
           "Active transport protein: pumps 3 Na+ OUT and 2 K+ IN per ATP hydrolyzed. Creates electrochemical gradients used for nerve impulses, muscle contraction, and secondary active transport. Net movement of positive charge out keeps cell interior negative.",
           "hard"),

        fc("ch4-fc-019", "4.4",
           "Endocytosis — phagocytosis, pinocytosis, receptor-mediated",
           "Endocytosis: cell engulfs extracellular material into a vesicle (uses energy). Phagocytosis ('cell eating'): ingests large particles/bacteria (macrophages). Pinocytosis ('cell drinking'): takes in fluid + dissolved solutes. Receptor-mediated: specific molecules bind surface receptors before engulfment.",
           "medium"),

        fc("ch4-fc-020", "4.4",
           "Exocytosis",
           "Vesicles inside the cell fuse with the plasma membrane and release contents outside. Used to secrete hormones (insulin), neurotransmitters, digestive enzymes, and extracellular matrix proteins. The opposite of endocytosis.",
           "easy"),
    ],
    "quiz": [
        q("ch4-q-001", "4.1",
          "Which statement correctly describes the First Law of Thermodynamics?",
          ["Energy tends to become less organized over time",
           "Energy cannot be created or destroyed, only converted from one form to another",
           "Reactions that release energy are always faster",
           "Living organisms can synthesize energy from matter"],
          1,
          "The First Law states that total energy is conserved. Cells cannot create energy; they convert chemical energy in glucose into ATP, heat, and mechanical work.",
          "medium"),

        q("ch4-q-002", "4.1",
          "Which of the following is an ENDERGONIC (energy-requiring) reaction?",
          ["Cellular respiration breaking down glucose to CO2 and H2O",
           "ATP hydrolysis releasing a phosphate group",
           "Photosynthesis building glucose from CO2 and H2O",
           "A burning match releasing heat and light"],
          2,
          "Photosynthesis builds glucose (a high-energy molecule) from low-energy CO2 and H2O — that requires energy input, making it endergonic. The others are exergonic (energy-releasing).",
          "medium"),

        q("ch4-q-003", "4.2",
          "When a cell hydrolyzes ATP to ADP + Pi, what is directly used to power cellular work?",
          ["The phosphate ion alone",
           "Free energy released from breaking the terminal phosphate bond",
           "Adenosine, which enters the citric acid cycle",
           "A proton gradient across the membrane"],
          1,
          "Hydrolysis of ATP releases ~7.3 kcal/mol of free energy. This energy is harnessed by coupling ATP hydrolysis to endergonic processes such as active transport, muscle contraction, and biosynthesis.",
          "easy"),

        q("ch4-q-004", "4.3",
          "An enzyme speeds up a reaction primarily by:",
          ["Increasing the free energy of the products",
           "Permanently changing the equilibrium of the reaction",
           "Lowering the activation energy required to initiate the reaction",
           "Increasing the concentration of substrate"],
          2,
          "Enzymes lower the activation energy barrier, allowing reactions to reach equilibrium faster. They do NOT change delta G or the equilibrium constant — only the rate at which equilibrium is achieved.",
          "medium"),

        q("ch4-q-005", "4.3",
          "The induced fit model of enzyme action states that:",
          ["The active site is rigid and only perfectly shaped substrates can bind",
           "The enzyme's active site changes shape slightly when substrate binds, improving catalysis",
           "Substrates reshape themselves to fit the rigid active site",
           "Enzymes are permanently changed after catalyzing one reaction"],
          1,
          "In the induced fit model, substrate binding triggers a conformational change in the enzyme that improves the enzyme-substrate interaction and promotes catalysis. This replaced the older, rigid 'lock-and-key' model.",
          "medium"),

        q("ch4-q-006", "4.3",
          "An enzyme that works at 37 degrees C is suddenly exposed to 90 degrees C. What happens?",
          ["The enzyme works faster due to higher kinetic energy of molecules",
           "The enzyme denatures — hydrogen bonds holding its 3D shape break and the active site is destroyed",
           "The enzyme becomes a competitive inhibitor",
           "Nothing — enzymes are not affected by temperature"],
          1,
          "Extreme heat disrupts the hydrogen bonds, hydrophobic interactions, and other forces maintaining an enzyme's tertiary structure. The protein unfolds (denatures) and can no longer bind substrate. Most human enzymes denature above ~45 degrees C.",
          "easy"),

        q("ch4-q-007", "4.3",
          "A drug molecule is shaped like the normal substrate and binds the enzyme's active site, blocking the reaction. The drug is acting as a:",
          ["Non-competitive inhibitor",
           "Coenzyme",
           "Competitive inhibitor",
           "Allosteric activator"],
          2,
          "A competitive inhibitor mimics the substrate and competes for the active site. The inhibition is reversible: adding more substrate can displace the inhibitor by out-competing it for access to the active site.",
          "medium"),

        q("ch4-q-008", "4.3",
          "An allosteric inhibitor binds a site OTHER than the active site and reduces enzyme activity. Adding more substrate:",
          ["Will overcome the inhibition because more substrate outcompetes the inhibitor",
           "Will have no effect — the inhibitor changes the enzyme's shape regardless of substrate concentration",
           "Will denature the inhibitor",
           "Will increase the activation energy of the reaction"],
          1,
          "Non-competitive (allosteric) inhibitors alter the enzyme's conformation by binding the allosteric site. Because they do not compete with the substrate for the active site, increasing substrate concentration cannot reverse the effect.",
          "hard"),

        q("ch4-q-009", "4.4",
          "A red blood cell placed in pure water will:",
          ["Shrink because the cell's solutes draw water in",
           "Stay the same size because its membrane is impermeable",
           "Swell and potentially burst as water enters by osmosis",
           "Lose solutes to equalize concentrations"],
          2,
          "Pure water is hypotonic to the red blood cell. Water moves by osmosis into the cell (toward higher solute concentration inside), causing the cell to swell and potentially lyse (osmotic lysis).",
          "medium"),

        q("ch4-q-010", "4.4",
          "Cucumbers shrivel when placed in very salty brine. This occurs because:",
          ["Salt actively pumps water out through transport proteins",
           "The brine is hypertonic; water exits cells by osmosis toward the higher solute concentration outside",
           "The brine is hypotonic; water rushes in and cells burst",
           "Salt denatures membrane transport proteins"],
          1,
          "High-salt brine is hypertonic relative to the cucumber cells. Water moves by osmosis out of cells (from higher water concentration inside to lower water concentration outside), causing the cells to shrink and the cucumber to shrivel.",
          "medium"),

        q("ch4-q-011", "4.4",
          "Glucose cannot diffuse through the lipid bilayer on its own. How does it enter most cells?",
          ["Active transport via the Na+/K+ pump",
           "Facilitated diffusion through GLUT carrier proteins — passive, no ATP required",
           "Endocytosis via phagocytosis",
           "Simple diffusion through the hydrophobic core"],
          1,
          "Glucose is polar and too large to cross the hydrophobic bilayer unaided. GLUT (glucose transporter) carrier proteins allow glucose to move by facilitated diffusion — down its concentration gradient without using ATP.",
          "medium"),

        q("ch4-q-012", "4.4",
          "The Na+/K+ pump moves ions AGAINST their concentration gradients. This is an example of:",
          ["Simple diffusion",
           "Facilitated diffusion",
           "Active transport — requires ATP to move substances from low to high concentration",
           "Osmosis"],
          2,
          "Active transport moves substances against their concentration gradient (uphill), which requires energy from ATP. The Na+/K+ pump hydrolyzes one ATP to move 3 Na+ out and 2 K+ in, against both ions' concentration gradients.",
          "medium"),

        q("ch4-q-013", "4.4",
          "Which pair of transport processes are BOTH passive (no ATP needed)?",
          ["Active transport and facilitated diffusion",
           "Simple diffusion and osmosis",
           "Endocytosis and exocytosis",
           "The Na+/K+ pump and pinocytosis"],
          1,
          "Both simple diffusion and osmosis are passive: they move substances or water down their concentration gradients without energy input. Active transport, endocytosis, and exocytosis all require ATP.",
          "easy"),

        q("ch4-q-014", "4.4",
          "A goblet cell in the intestinal lining secretes mucus into the intestinal lumen. Which process is used?",
          ["Phagocytosis",
           "Pinocytosis",
           "Exocytosis — vesicles fuse with the membrane to release contents outside",
           "Receptor-mediated endocytosis"],
          2,
          "Exocytosis is the process by which secretory vesicles (carrying mucus, hormones, enzymes, etc.) fuse with the plasma membrane and release their contents to the cell exterior.",
          "medium"),

        q("ch4-q-015", "4.4",
          "A white blood cell surrounds and engulfs a bacterial cell. Which process is this?",
          ["Exocytosis",
           "Pinocytosis",
           "Phagocytosis — a type of endocytosis for large solid particles",
           "Facilitated diffusion"],
          2,
          "Phagocytosis ('cell eating') is endocytosis of large solid particles. The white blood cell extends pseudopods around the bacterium, enclosing it in a phagosome that fuses with a lysosome for digestion.",
          "easy"),
    ],
}

# ─────────────────────────────────────────────────────────────────────────────
# CHAPTER 5 — PHOTOSYNTHESIS
# ─────────────────────────────────────────────────────────────────────────────
ch5 = {
    "id": "ch5",
    "title": "Photosynthesis",
    "sections": [
        {"id": "5.1", "title": "Life Depends on Photosynthesis"},
        {"id": "5.2", "title": "Chloroplasts Capture Light Energy"},
        {"id": "5.3", "title": "The Light Reactions"},
        {"id": "5.4", "title": "The Calvin Cycle Fixes Carbon"},
        {"id": "5.5", "title": "C3, C4, and CAM Plants"},
    ],
    "flashcards": [
        fc("ch5-fc-001", "5.1",
           "Overall equation for photosynthesis",
           "6 CO2 + 6 H2O + light energy -> C6H12O6 + 6 O2. Reactants: carbon dioxide (from air), water (from roots), and light energy. Products: glucose (stored chemical energy) and oxygen (released as a byproduct).",
           "easy"),

        fc("ch5-fc-002", "5.2",
           "Chloroplast structure: thylakoid vs. stroma",
           "Thylakoids: flattened membrane sacs stacked in grana; site of the LIGHT REACTIONS. Stroma: fluid surrounding the thylakoids; site of the CALVIN CYCLE (light-independent reactions). Chloroplast has two outer membranes (double envelope) plus thylakoid membranes.",
           "medium"),

        fc("ch5-fc-003", "5.2",
           "Chlorophyll a and b — light absorption",
           "Chlorophyll a: main photosynthetic pigment; absorbs violet-blue (~430 nm) and red (~680 nm); reflects green. Chlorophyll b: accessory pigment; absorbs blue (~453 nm) and orange-red (~642 nm); broadens absorption range. Both are found in the thylakoid membranes.",
           "medium"),

        fc("ch5-fc-004", "5.2",
           "Why do leaves look green?",
           "Chlorophylls absorb red and blue light strongly but reflect and transmit GREEN wavelengths. Our eyes detect the reflected green light. Leaves appear red/orange in fall when chlorophyll breaks down, revealing carotenoids.",
           "easy"),

        fc("ch5-fc-005", "5.2",
           "Carotenoids (carotenes and xanthophylls)",
           "Accessory pigments that absorb blue-green light (~400-500 nm) and reflect yellow, orange, and red. They extend the range of wavelengths used for photosynthesis and protect chlorophyll from excess light (photoprotection).",
           "medium"),

        fc("ch5-fc-006", "5.3",
           "Photosystem II (PSII) — P680",
           "Absorbs light at 680 nm. Light excites electrons in the reaction-center chlorophyll. Water molecules are split (photolysis: 2 H2O -> 4 H+ + 4 e- + O2) to replace the lost electrons. OXYGEN IS RELEASED AS A BYPRODUCT HERE.",
           "hard"),

        fc("ch5-fc-007", "5.3",
           "Electron transport chain between PSII and PSI",
           "Electrons from PSII pass through plastoquinone (PQ), the cytochrome b6f complex, and plastocyanin (PC). This electron flow pumps H+ into the thylakoid lumen, creating a proton gradient that drives ATP synthase (photophosphorylation).",
           "hard"),

        fc("ch5-fc-008", "5.3",
           "Photosystem I (PSI) — P700",
           "Absorbs light at 700 nm. Re-energizes electrons arriving from PSII. Electrons are passed to ferredoxin and then to NADP+ reductase, which reduces NADP+ + H+ -> NADPH. NADPH is an electron carrier used in the Calvin cycle.",
           "hard"),

        fc("ch5-fc-009", "5.3",
           "Products of the light reactions",
           "Three products: (1) ATP — from photophosphorylation via the proton gradient; (2) NADPH — electron carrier from PSI; (3) O2 — byproduct of water splitting at PSII. These products are used in the Calvin cycle. No glucose is made in the light reactions.",
           "medium"),

        fc("ch5-fc-010", "5.4",
           "Calvin cycle — location and summary",
           "Occurs in the STROMA. Three phases: (1) Carbon fixation: CO2 + RuBP (5C) -> 2 molecules of 3-PGA (3C), catalyzed by RuBisCO. (2) Reduction: ATP + NADPH convert 3-PGA -> G3P. (3) Regeneration of RuBP: G3P + ATP -> RuBP. Net: 1 G3P exits per 3 CO2 fixed.",
           "hard"),

        fc("ch5-fc-011", "5.4",
           "Role of RuBisCO",
           "Ribulose bisphosphate carboxylase-oxygenase (RuBisCO) is the enzyme that catalyzes carbon fixation: it adds CO2 to the 5-carbon acceptor RuBP, forming an unstable 6C compound that splits into two 3C molecules (3-PGA). It is the most abundant enzyme on Earth.",
           "medium"),

        fc("ch5-fc-012", "5.4",
           "G3P (glyceraldehyde-3-phosphate) — the Calvin cycle output",
           "G3P is the 3-carbon sugar produced by the Calvin cycle. It is the raw material for glucose, starch, cellulose, amino acids, and fatty acids. To make 1 glucose (6C), 2 G3P molecules are combined. To make 1 G3P, 3 CO2 are fixed and 9 ATP + 6 NADPH are consumed.",
           "medium"),

        fc("ch5-fc-013", "5.4",
           "Energy inputs and outputs of the Calvin cycle",
           "To fix 3 CO2 and produce 1 G3P: uses 9 ATP + 6 NADPH (from light reactions); releases 9 ADP + 8 Pi + 6 NADP+. The cycle regenerates its starting material (RuBP) and is powered entirely by the ATP and NADPH made in the light reactions.",
           "hard"),

        fc("ch5-fc-014", "5.5",
           "C3 plants",
           "First product of CO2 fixation is 3-phosphoglycerate (3-PGA), a 3-carbon molecule. Examples: wheat, rice, soybeans, most trees. In hot/dry conditions, C3 plants close stomata to conserve water, but this traps O2 and leads to PHOTORESPIRATION (RuBisCO fixes O2 instead of CO2), wasting energy.",
           "medium"),

        fc("ch5-fc-015", "5.5",
           "C4 plants — adapted to heat and high light",
           "First fix CO2 into a 4-carbon molecule (oxaloacetate) in mesophyll cells, then transport it to bundle-sheath cells where it releases CO2 for the Calvin cycle. This concentrates CO2 near RuBisCO, virtually eliminating photorespiration. Examples: corn, sugarcane, sorghum.",
           "medium"),

        fc("ch5-fc-016", "5.5",
           "CAM plants — adapted to arid environments",
           "Crassulacean Acid Metabolism: stomata open ONLY AT NIGHT to fix CO2 into malate (stored in vacuoles). During the day, stomata close (minimizing water loss) and stored CO2 is released for the Calvin cycle. Examples: cacti, agave, pineapple, aloe vera.",
           "medium"),

        fc("ch5-fc-017", "5.3",
           "Cyclic vs. non-cyclic photophosphorylation",
           "Non-cyclic: uses both PSII and PSI; produces ATP, NADPH, and O2; normal photosynthesis. Cyclic: electrons from PSI cycle back through the ETC to PSII; produces ONLY ATP (no NADPH, no O2). Used when the cell needs extra ATP but not NADPH.",
           "hard"),

        fc("ch5-fc-018", "5.2",
           "Absorption spectrum vs. action spectrum",
           "Absorption spectrum: shows which wavelengths of light a pigment absorbs (measured in a spectrophotometer). Action spectrum: shows which wavelengths drive photosynthesis most effectively (measured by O2 production or CO2 uptake). They closely match, confirming that light absorption drives photosynthesis.",
           "medium"),
    ],
    "quiz": [
        q("ch5-q-001", "5.1",
          "What are the REACTANTS and PRODUCTS of photosynthesis (overall equation)?",
          ["Reactants: O2 + glucose; Products: CO2 + H2O",
           "Reactants: CO2 + H2O + light; Products: glucose + O2",
           "Reactants: CO2 + ATP; Products: glucose + H2O",
           "Reactants: glucose + O2; Products: CO2 + H2O + ATP"],
          1,
          "Photosynthesis: 6 CO2 + 6 H2O + light energy -> C6H12O6 + 6 O2. Carbon dioxide and water are the raw materials; light provides the energy; glucose and oxygen are the outputs.",
          "easy"),

        q("ch5-q-002", "5.3",
          "Where in the chloroplast do the light reactions occur?",
          ["Stroma", "Outer membrane", "Thylakoid membranes", "Cytoplasm"],
          2,
          "The light reactions occur in and on the thylakoid membranes (in the grana). The ATP synthase, photosystems, and electron transport chain components are embedded in these membranes.",
          "easy"),

        q("ch5-q-003", "5.4",
          "Where in the chloroplast does the Calvin cycle occur?",
          ["Thylakoid lumen", "Stroma", "Grana", "Outer membrane"],
          1,
          "The Calvin cycle (light-independent reactions) takes place in the stroma — the fluid-filled space surrounding the thylakoids. The enzymes for carbon fixation and G3P production are dissolved in the stroma.",
          "easy"),

        q("ch5-q-004", "5.3",
          "The oxygen released during photosynthesis comes from:",
          ["Carbon dioxide being split",
           "Water molecules being split during the light reactions at PSII",
           "Glucose being broken down",
           "The Calvin cycle releasing O2 from CO2"],
          1,
          "During the light reactions, Photosystem II splits water (photolysis: 2 H2O -> 4 H+ + 4 e- + O2). The oxygen released into the atmosphere is entirely derived from water, not from CO2.",
          "medium"),

        q("ch5-q-005", "5.3",
          "Photosystem II (PSII) absorbs light at ~680 nm. What is produced at PSII?",
          ["NADPH and RuBP",
           "ATP only",
           "Excited electrons (passed to ETC), O2 (from water splitting), and H+ ions",
           "G3P and ADP"],
          2,
          "At PSII: light excites electrons in P680 chlorophyll. Water is split to replace those electrons, releasing O2 and H+. The excited electrons then enter the electron transport chain, driving ATP synthesis.",
          "hard"),

        q("ch5-q-006", "5.3",
          "What molecule does Photosystem I (PSI) ultimately produce?",
          ["ATP via photophosphorylation",
           "NADPH — the electron carrier used in the Calvin cycle",
           "O2 from water splitting",
           "G3P for glucose synthesis"],
          1,
          "PSI re-energizes electrons and passes them to NADP+ reductase, which reduces NADP+ to NADPH. NADPH carries electrons (reducing power) to the Calvin cycle to power carbon fixation and G3P production.",
          "medium"),

        q("ch5-q-007", "5.4",
          "What enzyme catalyzes carbon fixation in the Calvin cycle — adding CO2 to RuBP?",
          ["ATP synthase", "NADP+ reductase", "RuBisCO", "Helicase"],
          2,
          "RuBisCO (ribulose bisphosphate carboxylase-oxygenase) catalyzes the attachment of CO2 to the 5-carbon RuBP, the first step of the Calvin cycle. It is the most abundant enzyme on Earth.",
          "medium"),

        q("ch5-q-008", "5.4",
          "What does the Calvin cycle USE as inputs (besides CO2) and what does it directly PRODUCE?",
          ["Uses O2 and glucose; produces CO2 and H2O",
           "Uses ATP and NADPH (from light reactions) + CO2; produces G3P",
           "Uses only sunlight and CO2; produces RuBP",
           "Uses G3P; produces ATP and NADPH"],
          1,
          "The Calvin cycle uses ATP and NADPH (both products of the light reactions) plus CO2 to build G3P (glyceraldehyde-3-phosphate), the 3-carbon sugar used to construct glucose and other organic molecules.",
          "medium"),

        q("ch5-q-009", "5.4",
          "If the light reactions were suddenly blocked, what would happen to the Calvin cycle?",
          ["It would speed up because CO2 would build up",
           "It would continue using stored ATP and NADPH for several hours",
           "It would stop quickly because ATP and NADPH would be depleted",
           "It would switch to using O2 instead of CO2"],
          2,
          "The Calvin cycle depends entirely on ATP and NADPH produced by the light reactions. If light reactions stop, the supply of ATP and NADPH is quickly exhausted and the Calvin cycle halts.",
          "medium"),

        q("ch5-q-010", "5.5",
          "Corn is a C4 plant. How does C4 photosynthesis reduce photorespiration compared to C3 plants?",
          ["C4 plants close their stomata completely, so no O2 can enter",
           "C4 plants concentrate CO2 near RuBisCO in bundle-sheath cells, outcompeting O2 for the active site",
           "C4 plants do not use RuBisCO at all",
           "C4 plants only photosynthesize at night"],
          1,
          "C4 plants pre-fix CO2 into 4-carbon compounds in mesophyll cells and shuttle it to bundle-sheath cells, creating a high local CO2 concentration. This saturates RuBisCO with CO2, minimizing the oxygenase reaction (photorespiration) that wastes energy.",
          "medium"),

        q("ch5-q-011", "5.5",
          "A cactus is a CAM plant. How does it avoid water loss while still fixing CO2?",
          ["It fixes CO2 continuously through open stomata",
           "Its stomata are always closed; it fixes CO2 from stored water",
           "Stomata open ONLY AT NIGHT to absorb CO2; stomata are closed during the day to minimize water loss",
           "It uses O2 from water splitting instead of CO2"],
          2,
          "CAM plants open their stomata at night (when temperatures are lower and humidity is higher) to absorb CO2 and store it as malate. During the day, stomata close to prevent water loss and stored CO2 is released to power the Calvin cycle.",
          "medium"),

        q("ch5-q-012", "5.2",
          "Leaves appear green because chlorophyll:",
          ["Absorbs all wavelengths of visible light equally",
           "Absorbs green light and reflects all other wavelengths",
           "Absorbs red and blue light; reflects and transmits green light",
           "Emits green light through fluorescence during photosynthesis"],
          2,
          "Chlorophyll strongly absorbs red (~680 nm) and blue (~430 nm) light, using that energy for photosynthesis. Green light (~550 nm) is poorly absorbed and is reflected and transmitted — which is why we see leaves as green.",
          "easy"),

        q("ch5-q-013", "5.2",
          "What is the role of carotenoids in photosynthesis?",
          ["They are the only pigments that can absorb light",
           "They absorb blue-green wavelengths and transfer energy to chlorophyll, broadening the light-harvesting range",
           "They break down water to release oxygen",
           "They reduce NADP+ to NADPH"],
          1,
          "Carotenoids (carotenes and xanthophylls) are accessory pigments that capture light wavelengths (blue-green) that chlorophyll absorbs poorly. They transfer this energy to chlorophyll a reaction centers and also protect against excess light (photoprotection).",
          "medium"),

        q("ch5-q-014", "5.3",
          "Which statement about the relationship between the light reactions and the Calvin cycle is correct?",
          ["The light reactions are in the stroma; Calvin cycle is in the thylakoids",
           "They are completely independent; neither needs the other's products",
           "The light reactions produce ATP and NADPH that power the Calvin cycle; the Calvin cycle regenerates ADP, Pi, and NADP+ that the light reactions need",
           "The Calvin cycle produces light energy that drives the light reactions"],
          2,
          "The two stages are interdependent. Light reactions produce ATP and NADPH used in the Calvin cycle; the Calvin cycle produces ADP, Pi, and NADP+ that are recycled back to the light reactions. Neither can run without the other indefinitely.",
          "medium"),
    ],
}

# ─────────────────────────────────────────────────────────────────────────────
# CHAPTER 6 — CELLULAR RESPIRATION AND FERMENTATION
# ─────────────────────────────────────────────────────────────────────────────
ch6 = {
    "id": "ch6",
    "title": "Cellular Respiration and Fermentation",
    "sections": [
        {"id": "6.1", "title": "Cells Use Energy from Organic Molecules"},
        {"id": "6.2", "title": "Glycolysis Breaks Down Glucose to Pyruvate"},
        {"id": "6.3", "title": "Pyruvate Is Oxidized to Acetyl-CoA"},
        {"id": "6.4", "title": "The Krebs Cycle Extracts More Energy"},
        {"id": "6.5", "title": "The Electron Transport Chain and Chemiosmosis"},
        {"id": "6.6", "title": "Fermentation Supports Glycolysis Without Oxygen"},
    ],
    "flashcards": [
        fc("ch6-fc-001", "6.1",
           "Overall equation for aerobic cellular respiration",
           "C6H12O6 + 6 O2 -> 6 CO2 + 6 H2O + energy (ATP + heat). Glucose is oxidized; oxygen is the final electron acceptor; carbon is released as CO2; energy is captured as ~36-38 ATP (classical estimate; modern biochemistry suggests ~30-32 ATP per glucose).",
           "easy"),

        fc("ch6-fc-002", "6.1",
           "Cellular respiration is catabolic and exergonic",
           "Catabolism = breaking down complex molecules into simpler ones. Respiration dismantles glucose and releases the stored chemical energy as ATP. It is exergonic (negative delta G), proceeding spontaneously in a series of enzyme-controlled steps.",
           "medium"),

        fc("ch6-fc-003", "6.2",
           "Glycolysis — location and overview",
           "CYTOPLASM (cytosol). Glucose (6C) -> 2 pyruvate (3C). In two phases: energy investment (2 ATP used) and energy payoff (4 ATP + 2 NADH produced). Net gain: 2 ATP + 2 NADH. Does NOT require oxygen. Occurs in all living cells.",
           "medium"),

        fc("ch6-fc-004", "6.2",
           "Net products of glycolysis per glucose",
           "Net 2 ATP (4 produced - 2 invested), 2 NADH, and 2 pyruvate (3C). No CO2 is released during glycolysis. The 2 NADH will donate electrons to the ETC (if O2 is available) for further ATP production.",
           "medium"),

        fc("ch6-fc-005", "6.3",
           "Pyruvate oxidation (pyruvate decarboxylation)",
           "Occurs in the MITOCHONDRIAL MATRIX. Each pyruvate is converted: pyruvate -> acetyl-CoA (2C) + CO2 (1C released per pyruvate, so 2 CO2 per glucose) + 1 NADH. Acetyl-CoA enters the Krebs cycle. Net per glucose: 2 acetyl-CoA + 2 CO2 + 2 NADH.",
           "hard"),

        fc("ch6-fc-006", "6.4",
           "Krebs cycle (citric acid cycle) — location and overview",
           "MITOCHONDRIAL MATRIX. Acetyl-CoA (2C) combines with oxaloacetate (4C) -> citrate (6C) which is progressively oxidized back to oxaloacetate. Per cycle: 3 NADH, 1 FADH2, 1 ATP (GTP), 2 CO2 released. Two turns per glucose (2 acetyl-CoA).",
           "hard"),

        fc("ch6-fc-007", "6.4",
           "Krebs cycle products per glucose (2 turns)",
           "2 turns x each turn: 3 NADH, 1 FADH2, 1 ATP, 2 CO2. Totals per glucose: 6 NADH + 2 FADH2 + 2 ATP + 4 CO2. Combined with pyruvate oxidation: total CO2 released = 6 per glucose (2 from pyruvate ox + 4 from Krebs).",
           "hard"),

        fc("ch6-fc-008", "6.5",
           "Electron transport chain (ETC) — location",
           "INNER MITOCHONDRIAL MEMBRANE. NADH and FADH2 donate electrons to protein complexes (I, II, III, IV). Electrons pass down the chain to the final electron acceptor, O2, forming H2O. Energy released pumps H+ into the intermembrane space.",
           "medium"),

        fc("ch6-fc-009", "6.5",
           "Chemiosmosis and ATP synthase",
           "H+ ions pumped into the intermembrane space by the ETC flow back through ATP synthase (complex V) down their electrochemical gradient into the matrix. This proton flow powers the rotation of ATP synthase, which phosphorylates ADP -> ATP. This is oxidative phosphorylation.",
           "hard"),

        fc("ch6-fc-010", "6.5",
           "Why is oxygen the final electron acceptor?",
           "Oxygen has a very high electronegativity and pulls electrons strongly. At the end of the ETC, 4 electrons + 4 H+ + O2 -> 2 H2O. Without O2 to accept electrons, the ETC backs up, H+ gradient collapses, and ATP synthase stops — aerobic respiration ceases.",
           "medium"),

        fc("ch6-fc-011", "6.5",
           "Total ATP yield from aerobic respiration",
           "Classical estimate: ~36-38 ATP per glucose. Modern estimate: ~30-32 ATP. Breakdown: glycolysis (2 ATP), Krebs (2 ATP), oxidative phosphorylation via NADH (~2.5 ATP each x 10 = 25) and FADH2 (~1.5 ATP each x 2 = 3). Actual yield varies by conditions.",
           "medium"),

        fc("ch6-fc-012", "6.5",
           "Where is CO2 released during aerobic respiration?",
           "CO2 is released ONLY during pyruvate oxidation and the Krebs cycle — NOT during glycolysis or the ETC. Per glucose: 2 CO2 from pyruvate oxidation + 4 CO2 from Krebs = 6 CO2 total. This matches the overall equation (6 CO2 per glucose).",
           "medium"),

        fc("ch6-fc-013", "6.6",
           "Fermentation — purpose and key feature",
           "Fermentation regenerates NAD+ from NADH so that glycolysis can continue without oxygen. NAD+ is a required electron carrier for glycolysis. WITHOUT fermentation (or an ETC), cells would run out of NAD+, glycolysis would stop, and ATP production would cease entirely. Fermentation itself produces no additional ATP beyond glycolysis's 2 ATP.",
           "hard"),

        fc("ch6-fc-014", "6.6",
           "Lactic acid fermentation",
           "Pyruvate + NADH -> lactate + NAD+. Occurs in: human muscle cells during intense exercise (lactate buildup causes burning sensation); bacteria used in yogurt, cheese, sauerkraut, and kimchi. Lactate can be converted back to pyruvate in the liver (Cori cycle) when O2 is again available.",
           "medium"),

        fc("ch6-fc-015", "6.6",
           "Alcoholic (ethanol) fermentation",
           "Pyruvate -> acetaldehyde + CO2 (by pyruvate decarboxylase), then acetaldehyde + NADH -> ethanol + NAD+ (by alcohol dehydrogenase). Occurs in yeast. Used in: bread rising (CO2 causes dough to expand), beer, wine, and spirits. Humans cannot reverse this to produce energy from ethanol the same way.",
           "medium"),

        fc("ch6-fc-016", "6.6",
           "Aerobic respiration vs. fermentation — ATP comparison",
           "Aerobic respiration: ~36-38 ATP per glucose (uses ETC + chemiosmosis). Fermentation: only 2 ATP per glucose (glycolysis only). Fermentation is ~18-19x less efficient but works WITHOUT oxygen. Organisms switch to fermentation when O2 is unavailable.",
           "medium"),

        fc("ch6-fc-017", "6.5",
           "Role of NADH and FADH2 in aerobic respiration",
           "NADH and FADH2 are electron carriers produced in glycolysis, pyruvate oxidation, and the Krebs cycle. They deliver electrons (and their energy) to the ETC. Each NADH yields ~2.5 ATP; each FADH2 yields ~1.5 ATP. Without them, the ETC cannot pump H+ and ATP synthase cannot generate ATP.",
           "hard"),

        fc("ch6-fc-018", "6.1",
           "Stages of aerobic respiration and their locations",
           "1) Glycolysis: CYTOPLASM. 2) Pyruvate oxidation: MITOCHONDRIAL MATRIX. 3) Krebs cycle: MITOCHONDRIAL MATRIX. 4) Electron transport chain + chemiosmosis: INNER MITOCHONDRIAL MEMBRANE. Knowing these locations is essential for exam questions.",
           "medium"),

        fc("ch6-fc-019", "6.2",
           "Why glycolysis is universal",
           "Glycolysis occurs in the CYTOSOL of virtually all living cells — prokaryotes and eukaryotes alike. It predates mitochondria evolutionarily, operates anaerobically, and provides the starting point for both aerobic respiration and fermentation. It requires no special organelle.",
           "medium"),

        fc("ch6-fc-020", "6.5",
           "Comparing the inner mitochondrial membrane to the thylakoid membrane",
           "Both use an electron transport chain and ATP synthase powered by a proton (H+) gradient. Mitochondrion: electrons from NADH/FADH2, final acceptor is O2, H+ pumped into intermembrane space. Thylakoid: electrons from water, pumped into thylakoid lumen. Both = chemiosmosis.",
           "hard"),
    ],
    "quiz": [
        q("ch6-q-001", "6.2",
          "In which part of the cell does glycolysis occur?",
          ["Mitochondrial matrix",
           "Inner mitochondrial membrane",
           "Cytoplasm (cytosol)",
           "Nucleus"],
          2,
          "Glycolysis occurs in the cytoplasm (cytosol). It requires no mitochondria, which is why even prokaryotes (which lack mitochondria) perform glycolysis.",
          "easy"),

        q("ch6-q-002", "6.2",
          "What is the NET ATP gain from glycolysis?",
          ["4 ATP", "2 ATP", "36 ATP", "0 ATP — glycolysis consumes all ATP it makes"],
          1,
          "Glycolysis invests 2 ATP to break down glucose, then produces 4 ATP in the payoff phase: net gain = 4 - 2 = 2 ATP per glucose. It also produces 2 NADH and 2 pyruvate.",
          "easy"),

        q("ch6-q-003", "6.2",
          "Which statement about glycolysis is correct?",
          ["It requires oxygen",
           "It occurs in the mitochondrial matrix",
           "It produces 2 pyruvate, 2 NADH, and a net 2 ATP per glucose",
           "It releases CO2 as a byproduct"],
          2,
          "Glycolysis splits glucose (6C) into 2 pyruvate (3C each), producing 2 NADH and a net 2 ATP. No O2 is required and no CO2 is released.",
          "medium"),

        q("ch6-q-004", "6.5",
          "What is the FINAL electron acceptor at the end of the electron transport chain in aerobic respiration?",
          ["NAD+", "CO2", "Oxygen (O2)", "ADP"],
          2,
          "Oxygen is the final electron acceptor in the ETC. It combines with electrons and H+ to form water (2 H2O). Without O2, the ETC cannot accept more electrons, shuts down, and ATP synthesis via chemiosmosis stops.",
          "easy"),

        q("ch6-q-005", "6.4",
          "Where does the Krebs cycle occur?",
          ["Cytoplasm",
           "Inner mitochondrial membrane",
           "Thylakoid membrane",
           "Mitochondrial matrix"],
          3,
          "Both pyruvate oxidation and the Krebs cycle take place in the mitochondrial matrix, the aqueous compartment enclosed by the inner mitochondrial membrane.",
          "easy"),

        q("ch6-q-006", "6.4",
          "For EACH turn of the Krebs cycle (per acetyl-CoA), what is produced?",
          ["4 NADH, 2 FADH2, 2 ATP, 1 CO2",
           "3 NADH, 1 FADH2, 1 ATP, 2 CO2",
           "2 NADH, 2 FADH2, 2 ATP, 2 CO2",
           "1 NADH, 1 FADH2, 2 ATP, 4 CO2"],
          1,
          "Per turn: 3 NADH, 1 FADH2, 1 ATP (via GTP), and 2 CO2. Since 2 acetyl-CoA enter per glucose, the Krebs cycle runs twice per glucose, doubling these totals.",
          "hard"),

        q("ch6-q-007", "6.5",
          "What drives ATP synthase in the mitochondrion during aerobic respiration?",
          ["Direct transfer of phosphate from pyruvate",
           "The flow of electrons from NADH to O2",
           "H+ ions flowing back into the matrix through ATP synthase down their electrochemical gradient (chemiosmosis)",
           "CO2 released from the Krebs cycle"],
          2,
          "The ETC pumps H+ into the intermembrane space. H+ ions flow back into the matrix through ATP synthase, and this proton flow powers the mechanical rotation of ATP synthase, which phosphorylates ADP to ATP (chemiosmosis / oxidative phosphorylation).",
          "hard"),

        q("ch6-q-008", "6.6",
          "The PRIMARY purpose of fermentation is to:",
          ["Produce more ATP when oxygen is scarce",
           "Regenerate NAD+ from NADH so that glycolysis can continue producing ATP",
           "Break down pyruvate into CO2 and water",
           "Power the electron transport chain without oxygen"],
          1,
          "Glycolysis needs NAD+ to accept electrons. Fermentation oxidizes NADH back to NAD+ (transferring electrons to pyruvate to make lactate or ethanol) so glycolysis can keep running. Fermentation itself generates no new ATP.",
          "hard"),

        q("ch6-q-009", "6.6",
          "Which products are formed during LACTIC ACID fermentation?",
          ["Ethanol + CO2 + NAD+",
           "Lactate + NAD+",
           "Acetyl-CoA + NADH + CO2",
           "Glucose + O2"],
          1,
          "In lactic acid fermentation, pyruvate accepts electrons from NADH, forming lactate and regenerating NAD+. No CO2 is released. This occurs in muscle cells during intense exercise and in bacteria used for yogurt and cheese.",
          "medium"),

        q("ch6-q-010", "6.6",
          "Bread rises because yeast perform alcoholic fermentation. What gas is responsible for the bubbles?",
          ["Oxygen", "Lactate", "Carbon dioxide (CO2)", "Ethanol vapor"],
          2,
          "During alcoholic fermentation, pyruvate is converted to ethanol and CO2. The CO2 gas becomes trapped in dough, causing it to rise. The ethanol evaporates during baking.",
          "easy"),

        q("ch6-q-011", "6.5",
          "Compared to fermentation, aerobic respiration produces approximately how much more ATP per glucose?",
          ["2x more", "5x more", "18x more", "They produce the same amount"],
          2,
          "Fermentation yields only 2 ATP (glycolysis alone). Aerobic respiration yields ~36-38 ATP (or ~30-32 by modern estimates). That is roughly 18-19 times more ATP, due to the ETC and oxidative phosphorylation.",
          "medium"),

        q("ch6-q-012", "6.5",
          "If oxygen is suddenly removed from a cell performing aerobic respiration, the ETC will stop because:",
          ["There is no more glucose to oxidize",
           "NADH cannot be produced without O2",
           "O2 is needed as the final electron acceptor; without it electrons pile up and the chain backs up",
           "ATP synthase requires O2 to rotate"],
          2,
          "O2 is indispensable as the terminal electron acceptor. If O2 is absent, electrons accumulate at the end of the ETC, the chain backs up, H+ is no longer pumped, the proton gradient collapses, and ATP synthase stops. The cell must switch to fermentation.",
          "medium"),

        q("ch6-q-013", "6.4",
          "How many total CO2 molecules are released per glucose during aerobic respiration (pyruvate oxidation + Krebs)?",
          ["2 CO2", "4 CO2", "6 CO2", "12 CO2"],
          2,
          "2 CO2 are released during pyruvate oxidation (1 per pyruvate x 2 pyruvate) + 4 CO2 from two turns of the Krebs cycle (2 per turn) = 6 CO2 total per glucose. This matches the overall equation: C6H12O6 + 6 O2 -> 6 CO2 + 6 H2O.",
          "medium"),

        q("ch6-q-014", "6.2",
          "During a sprint, muscle cells run out of oxygen and must rely on fermentation. The burning feeling is due to:",
          ["ATP accumulation in the muscle fibers",
           "CO2 buildup in the muscle",
           "Lactate accumulation from lactic acid fermentation",
           "Ethanol produced by alcoholic fermentation"],
          2,
          "In oxygen-depleted muscle cells, lactic acid fermentation produces lactate from pyruvate, regenerating NAD+ to sustain glycolysis. Lactate accumulation lowers pH and contributes to the burning sensation and muscle fatigue during intense exercise.",
          "easy"),

        q("ch6-q-015", "6.5",
          "Which location in the cell produces the MOST ATP during aerobic respiration?",
          ["Cytoplasm during glycolysis",
           "Mitochondrial matrix during the Krebs cycle",
           "Inner mitochondrial membrane via the ETC and ATP synthase",
           "Nucleus during DNA replication"],
          2,
          "The vast majority of ATP (~32-34 of the ~36-38 total) is produced at the inner mitochondrial membrane through oxidative phosphorylation — electrons from NADH and FADH2 drive the ETC, which powers ATP synthase via chemiosmosis.",
          "medium"),
    ],
}

# ─────────────────────────────────────────────────────────────────────────────
# MERGE AND WRITE
# ─────────────────────────────────────────────────────────────────────────────

# Append extra questions to existing chapters
for ch in data["chapters"]:
    if ch["id"] == "ch1":
        ch["quiz"].extend(ch1_extra_quiz)
    elif ch["id"] == "ch2":
        ch["quiz"].extend(ch2_extra_quiz)
    elif ch["id"] == "ch3":
        ch["quiz"].extend(ch3_extra_quiz)

# Append new chapters (only if not already present)
existing_ids = {ch["id"] for ch in data["chapters"]}
for new_ch in [ch4, ch5, ch6]:
    if new_ch["id"] not in existing_ids:
        data["chapters"].append(new_ch)

# Write output
for path in ["src/data/content.json", "content.json"]:
    with open(path, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2, ensure_ascii=False)

# Summary
print("Done! Chapter quiz counts:")
for ch in data["chapters"]:
    print(f"  {ch['id']}: {len(ch['flashcards'])} flashcards, {len(ch['quiz'])} quiz questions")
